// <auto-generated />
using KoPagesa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoPagesa.Migrations
{
    [DbContext(typeof(PerdoruesitContext))]
    [Migration("20221227213447_Perdoruesi")]
    partial class Perdoruesi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoPagesa.Models.Perdoruesi", b =>
                {
                    b.Property<int>("PerdoruesiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerdoruesiId"));

                    b.Property<string>("Emaili")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("Fjalkalimi")
                        .IsRequired()
                        .HasColumnType("nvarchar (30)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.HasKey("PerdoruesiId");

                    b.ToTable("perdoruesi");
                });
#pragma warning restore 612, 618
        }
    }
}
