// <auto-generated />
using KoPagesa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoPagesa.Migrations
{
    [DbContext(typeof(PerdoruesitContext))]
    [Migration("20230203214019_KompaniteAdd")]
    partial class KompaniteAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoPagesa.Models.Patenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataLeshimit")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("DataLindjes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSkadences")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<bool>("EAktivizuar")
                        .HasColumnType("bit");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("Fotografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komuna")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("NumriPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar (45)");

                    b.HasKey("Id");

                    b.ToTable("patenta");
                });

            modelBuilder.Entity("KoPagesa.Models.Perdoruesi", b =>
                {
                    b.Property<int>("PerdoruesiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerdoruesiId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emaili")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fjalkalimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Njoftime")
                        .HasColumnType("int");

                    b.Property<string>("NumriPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Roli")
                        .HasColumnType("int");

                    b.HasKey("PerdoruesiId");

                    b.ToTable("perdoruesi");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Perdoruesi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KoPagesa.Models.Klienti", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Perdoruesi");

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("DataSkadimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KartelaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MbajtesiKarteles")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumriKarteles")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Klienti");
                });

            modelBuilder.Entity("KoPagesa.Models.Sherbyesi", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Perdoruesi");

                    b.Property<string>("NumriFiskal")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Sherbyesi");
                });

            modelBuilder.Entity("KoPagesa.Models.KompaniaInternetit", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Sherbyesi");

                    b.Property<double>("ShpejtesiaInternetit")
                        .HasColumnType("float");

                    b.Property<string>("nrBiznesit")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("KompaniaInternetit");
                });

            modelBuilder.Entity("KoPagesa.Models.KompaniaMbeturinave", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Sherbyesi");

                    b.Property<int>("NumriKamioneve")
                        .HasColumnType("int");

                    b.Property<string>("nrBiznesit")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("KompaniaMbeturinave");
                });

            modelBuilder.Entity("KoPagesa.Models.KompaniaUjit", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Sherbyesi");

                    b.Property<double>("FaktoriPH")
                        .HasColumnType("float");

                    b.Property<string>("nrBiznesit")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("KompaniaUjit");
                });

            modelBuilder.Entity("KoPagesa.Models.Policia", b =>
                {
                    b.HasBaseType("KoPagesa.Models.Sherbyesi");

                    b.Property<string>("StacioniPolicor")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Policia");
                });
#pragma warning restore 612, 618
        }
    }
}
